/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksRouteRouteImport } from './routes/books/route'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBooksImportRouteImport } from './routes/api/books/import'
import { Route as BooksTransactionsIndexRouteImport } from './routes/books/transactions/index'
import { Route as BooksAdminUsersIndexRouteImport } from './routes/books/admin/users/index'
import { Route as BooksBankingImportIndexRouteImport } from './routes/books/banking/import/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRouteRoute = BooksRouteRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksImportRoute = ApiBooksImportRouteImport.update({
  id: '/api/books/import',
  path: '/api/books/import',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksTransactionsIndexRoute = BooksTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => BooksRouteRoute,
} as any)
const BooksAdminUsersIndexRoute = BooksAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => BooksRouteRoute,
} as any)
const BooksBankingImportIndexRoute = BooksBankingImportIndexRouteImport.update({
  id: '/banking/import/',
  path: '/banking/import/',
  getParentRoute: () => BooksRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/books/import': typeof ApiBooksImportRoute
  '/books/transactions/': typeof BooksTransactionsIndexRoute
  '/books/admin/users/': typeof BooksAdminUsersIndexRoute
  '/books/banking/import/': typeof BooksBankingImportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/books/import': typeof ApiBooksImportRoute
  '/books/transactions': typeof BooksTransactionsIndexRoute
  '/books/admin/users': typeof BooksAdminUsersIndexRoute
  '/books/banking/import': typeof BooksBankingImportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteRouteWithChildren
  '/books/': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/books/import': typeof ApiBooksImportRoute
  '/books/transactions/': typeof BooksTransactionsIndexRoute
  '/books/admin/users/': typeof BooksAdminUsersIndexRoute
  '/books/banking/import/': typeof BooksBankingImportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/books/'
    | '/api/auth/$'
    | '/api/books/import'
    | '/books/transactions/'
    | '/books/admin/users/'
    | '/books/banking/import/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/api/auth/$'
    | '/api/books/import'
    | '/books/transactions'
    | '/books/admin/users'
    | '/books/banking/import'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/books/'
    | '/api/auth/$'
    | '/api/books/import'
    | '/books/transactions/'
    | '/books/admin/users/'
    | '/books/banking/import/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRouteRoute: typeof BooksRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBooksImportRoute: typeof ApiBooksImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/import': {
      id: '/api/books/import'
      path: '/api/books/import'
      fullPath: '/api/books/import'
      preLoaderRoute: typeof ApiBooksImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/transactions/': {
      id: '/books/transactions/'
      path: '/transactions'
      fullPath: '/books/transactions/'
      preLoaderRoute: typeof BooksTransactionsIndexRouteImport
      parentRoute: typeof BooksRouteRoute
    }
    '/books/admin/users/': {
      id: '/books/admin/users/'
      path: '/admin/users'
      fullPath: '/books/admin/users/'
      preLoaderRoute: typeof BooksAdminUsersIndexRouteImport
      parentRoute: typeof BooksRouteRoute
    }
    '/books/banking/import/': {
      id: '/books/banking/import/'
      path: '/banking/import'
      fullPath: '/books/banking/import/'
      preLoaderRoute: typeof BooksBankingImportIndexRouteImport
      parentRoute: typeof BooksRouteRoute
    }
  }
}

interface BooksRouteRouteChildren {
  BooksIndexRoute: typeof BooksIndexRoute
  BooksTransactionsIndexRoute: typeof BooksTransactionsIndexRoute
  BooksAdminUsersIndexRoute: typeof BooksAdminUsersIndexRoute
  BooksBankingImportIndexRoute: typeof BooksBankingImportIndexRoute
}

const BooksRouteRouteChildren: BooksRouteRouteChildren = {
  BooksIndexRoute: BooksIndexRoute,
  BooksTransactionsIndexRoute: BooksTransactionsIndexRoute,
  BooksAdminUsersIndexRoute: BooksAdminUsersIndexRoute,
  BooksBankingImportIndexRoute: BooksBankingImportIndexRoute,
}

const BooksRouteRouteWithChildren = BooksRouteRoute._addFileChildren(
  BooksRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRouteRoute: BooksRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBooksImportRoute: ApiBooksImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
